# Generated by Django 3.1.7 on 2021-04-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='cr',
            new_name='xp',
        ),
    ]
