# Generated by Django 3.1.7 on 2021-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_auto_20210418_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='abbr_name',
            field=models.CharField(max_length=12, unique=True, verbose_name='Abbreviated name'),
        ),
    ]
