# Generated by Django 3.1.7 on 2021-05-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20210504_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
    ]
