# Generated by Django 3.1.7 on 2021-05-15 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_tag_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='pages',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
