# Generated by Django 3.1.7 on 2021-05-18 19:06

import django.core.validators
from django.db import migrations, models
import monsters.models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_source_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='page',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(monsters.models.Monster.get_source_pages)]),
        ),
    ]
