# Generated by Django 3.1.7 on 2021-05-18 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0007_auto_20210518_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='page',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
