# Generated by Django 3.1.7 on 2021-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0008_auto_20210518_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
