# Generated by Django 3.1.7 on 2021-05-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0011_auto_20210522_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-official', 'abbr_name']},
        ),
    ]
