# Generated by Django 3.1.7 on 2021-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0013_monster_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_form', models.CharField(max_length=10)),
                ('int_form', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='monster',
            name='xp',
        ),
    ]
